### ISSUE TITLE
no matching function for call to 'Property()

### ISSUE THREAD

**Issue by porlock** [luisllamasbinaburo/Arduino-ReactiveArduino#4]
On this simple code 
```
#include <Arduino.h>
#include "ReactiveArduinoLib.h"

auto observableInt = Reactive::Property();
```
i got this error
```
src\main.cpp:4:41: error: no matching function for call to 'Property()'
 auto observableInt = Reactive::Property();
```

**Comment by luisllamasbinaburo** [comment]
Check this example
https://github.com/luisllamasbinaburo/Arduino-ReactiveArduino/blob/master/examples/FromProperty/FromProperty.ino

**Comment by vgb1993** [comment]
Same issue with me, perhaps we could edit this example:

`
#include "ReactiveArduinoLib.h"

auto observableInt = Reactive::Property();

void setup()
{
	Serial.begin(115200);
	while (!Serial) delay(1);

	observableInt
	.ToSerial();
}

void loop()
{
	delay(1000);
	observableInt = 1;
	delay(1000);
	observableInt = 2;
	delay(1000);
	observableInt = 2;
	delay(1000);
	observableInt = 3;
}
`


To this:

`
#include "ReactiveArduinoLib.h"

ObservableProperty<int> observableInt;

void setup()
{
	Serial.begin(115200);
	while (!Serial) delay(1);

	observableInt
	.ToSerial();
}

void loop()
{
	delay(1000);
	observableInt = 1;
	delay(1000);
	observableInt = 2;
	delay(1000);
	observableInt = 2;
	delay(1000);
	observableInt = 3;
}
`
